export class AudioSystem {
  constructor(){this.ctx=null;this.master=null;this.engineOsc=null;this.engineGain=null;this.wind=null;this.enabled=true}
  init(){if(!this.enabled)return;try{this.ctx??=new(window.AudioContext||window.webkitAudioContext)();if(this.ctx.state==='suspended')this.ctx.resume();if(this.master)return;this.master=this.ctx.createGain();this.master.gain.value=.28;this.master.connect(this.ctx.destination);this.engineOsc=this.ctx.createOscillator();this.engineOsc.type='sawtooth';this.engineOsc.frequency.value=58;this.engineGain=this.ctx.createGain();this.engineGain.gain.value=.018;this.engineOsc.connect(this.engineGain).connect(this.master);this.engineOsc.start();this.wind=this.ctx.createOscillator();this.wind.type='triangle';this.wind.frequency.value=42;let filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=170;this.windGain=this.ctx.createGain();this.windGain.gain.value=0;this.wind.connect(filter).connect(this.windGain).connect(this.master);this.wind.start()}catch{this.enabled=false}}
  tone(freq,endFreq,duration,type='sawtooth',gain=.12,pan=0){if(!this.enabled)return;this.init();if(!this.ctx||!this.master)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),p=this.ctx.createStereoPanner?.();o.type=type;o.frequency.setValueAtTime(freq,this.ctx.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(12,endFreq),this.ctx.currentTime+duration);g.gain.setValueAtTime(gain,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,this.ctx.currentTime+duration);if(p){p.pan.value=pan;o.connect(g).connect(p).connect(this.master)}else o.connect(g).connect(this.master);o.start();o.stop(this.ctx.currentTime+duration+.01)}
  noise(duration,gain=.14,filterFreq=900){if(!this.enabled)return;this.init();if(!this.ctx)return;const size=Math.floor(this.ctx.sampleRate*duration),buffer=this.ctx.createBuffer(1,size,this.ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<size;i++)data[i]=(Math.random()*2-1)*(1-i/size);const src=this.ctx.createBufferSource();src.buffer=buffer;const filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=filterFreq;const amp=this.ctx.createGain();amp.gain.setValueAtTime(gain,this.ctx.currentTime);amp.gain.exponentialRampToValueAtTime(.001,this.ctx.currentTime+duration);src.connect(filter).connect(amp).connect(this.master);src.start()}
  shot(){this.tone(760,105,.095,'sawtooth',.07);this.tone(1120,380,.065,'triangle',.035)}
  hit(){this.tone(590,230,.11,'sine',.08);this.noise(.075,.04,1600)}
  reload(){this.tone(180,440,.16,'square',.045);setTimeout(()=>this.tone(460,180,.22,'triangle',.055),240)}
  explosion(){this.noise(.5,.3,340);this.tone(110,28,.52,'sine',.25)}
  damage(){this.tone(130,50,.32,'sawtooth',.14,-.4)}
  boost(on){this.init();if(this.windGain&&this.ctx){const t=this.ctx.currentTime;this.windGain.gain.cancelScheduledValues(t);this.windGain.gain.setTargetAtTime(on?.11:0,t,.18);this.wind.frequency.setTargetAtTime(on?115:42,t,.2)}}
  flight(speed,boost){this.init();if(!this.engineOsc||!this.ctx)return;const t=this.ctx.currentTime;this.engineOsc.frequency.setTargetAtTime(55+Math.min(100,speed*5)+(boost?35:0),t,.14);this.engineGain.gain.setTargetAtTime(.014+Math.min(.04,speed*.0012)+(boost?.02:0),t,.15)}
  dispose(){if(this.ctx)this.ctx.close();this.ctx=null}
}
