import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.164.1/build/three.module.js';

const WEAPON={name:'ARC-9',capacity:24,damage:26,rate:.105,reload:1.35,color:0x73efff,spread:.008,mode:'ENERGY REPEATER'};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export class CombatSystem {
  constructor(scene,camera,effects,onEvent=()=>{}){this.scene=scene;this.camera=camera;this.effects=effects;this.onEvent=onEvent;this.raycaster=new THREE.Raycaster();this.ammo=WEAPON.capacity;this.cooldown=0;this.reload=0;this.score=0;this.enemyScore=0;this.hostiles=[];this.allBots=[];this.enemyFire=0;this.botFireTimer=0;this.hitTime=0;this.focus=false;this.targetObjects=[];this.weapon=WEAPON;this.playerHits=0;this.timer=0;this.shots=0}
  reset(hostiles,allBots=hostiles){this.allBots=allBots;this.ammo=WEAPON.capacity;this.cooldown=0;this.reload=0;this.score=0;this.enemyScore=0;this.hostiles=hostiles;this.enemyFire=999;this.botFireTimer=.65;this.hitTime=0;this.playerHits=0;this.timer=0;this.shots=0}
  shoot(origin,aim,focus=false,muzzlePositions=[]){if(this.cooldown>0||this.reload>0)return false;if(this.ammo<=0){this.reloadWeapon();return false}const w=this.weapon;this.ammo--;this.shots++;this.cooldown=w.rate;const spread=focus?w.spread*.24:w.spread;const direction=aim.clone().add(new THREE.Vector3((Math.random()-.5)*spread,(Math.random()-.5)*spread,(Math.random()-.5)*spread)).normalize();for(const muzzle of muzzlePositions)this.effects.muzzle(muzzle,direction,w.color,.85);if(!muzzlePositions.length)this.effects.muzzle(origin,direction,w.color,1);this.raycaster.set(origin,direction);this.raycaster.far=140;this.targetObjects.length=0;for(const bot of this.allBots)if(bot.alive){bot.group.updateMatrixWorld(true);this.targetObjects.push(...bot.hitMeshes)}const hits=this.raycaster.intersectObjects(this.targetObjects,false);const bulletStart=muzzlePositions[0]||origin;const bulletEnd=hits.length?hits[0].point:origin.clone().addScaledVector(direction,105);this.effects.tracer(bulletStart,bulletEnd,w.color,.014,.075);if(hits.length){const hit=hits[0],bot=this.allBots.find(x=>x.alive&&x.hitMeshes.includes(hit.object));if(bot){bot.health-=w.damage;bot.group.userData.flash=.14;this.hitTime=.12;this.score+=1;const hitNormal=hit.face?.normal?.clone().transformDirection(bot.group.matrixWorld)||direction.clone().negate();this.effects.impact(hit.point,hitNormal,w.color,.8);this.onEvent('hit',bot);if(bot.health<=0){bot.alive=false;bot.group.visible=false;this.score+=90;this.onEvent('elimination',bot,origin)}return true}}
    return true;
  }
  reloadWeapon(){if(this.reload<=0&&this.ammo<this.weapon.capacity){this.reload=this.weapon.reload;this.onEvent('reload') }}
  focusOn(value){this.focus=value}
  damagePlayer(state,amount){state.health=Math.max(0,state.health-amount);this.playerHits++;this.onEvent('playerDamage',amount);if(state.health===0)this.onEvent('destroyed')}
  updateBots(dt,game,bots,effects){this.botFireTimer-=dt;if(this.botFireTimer>0||game.mode!=='match')return;const red=bots.filter(bot=>bot.team==='red'&&bot.alive),blue=bots.filter(bot=>bot.team==='blue'&&bot.alive);for(const bot of [...red,...blue]){let target;if(bot.team==='red')target=game.drone;else target=red.sort((a,b)=>a.group.position.distanceTo(bot.group.position)-b.group.position.distanceTo(bot.group.position))[0];if(!target)continue;const point=bot.team==='red'?target.position:target.group.position,origin=bot.group.position.clone(),direction=point.clone().sub(origin).normalize();effects.tracer(origin,point,bot.team==='red'?0xff5289:0x50dfff,.023,.17);if(bot.team==='red'){if(bot.group.position.distanceTo(game.drone.position)<55)this.damagePlayer(game,1+Math.random()*1.4)}else{target.health-=8;if(target.health<=0){target.alive=false;target.respawn=2.6;target.group.visible=false;this.onEvent('botElimination',bot,target)}}}this.botFireTimer=.9+Math.random()*.55}
  update(dt,state){this.cooldown=Math.max(0,this.cooldown-dt);this.hitTime=Math.max(0,this.hitTime-dt);if(this.reload>0){this.reload=Math.max(0,this.reload-dt);if(this.reload===0){this.ammo=this.weapon.capacity;this.onEvent('reloaded')}}if(state.mode!=='match')return;this.timer+=dt;this.enemyFire-=dt;
    
  }
}
export {WEAPON};
