import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.164.1/build/three.module.js';

const $=s=>document.querySelector(s), canvas=$('#world');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const scene=new THREE.Scene();scene.background=new THREE.Color('#91a4a5');scene.fog=new THREE.FogExp2('#91a4a5',.012);
const camera=new THREE.PerspectiveCamera(76,innerWidth/innerHeight,.08,180);camera.rotation.order='YXZ';scene.add(camera);
const hemi=new THREE.HemisphereLight('#d4eff0','#404238',2.1);scene.add(hemi);
const sun=new THREE.DirectionalLight('#fff1c8',3.2);sun.position.set(-18,30,-12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-45;sun.shadow.camera.right=45;sun.shadow.camera.top=45;sun.shadow.camera.bottom=-45;scene.add(sun);
let world=new THREE.Group();scene.add(world);let fx=new THREE.Group();scene.add(fx);
const missions=[
 {name:'Ghost Signal',code:'OP-01 / INSERTION',sector:'KARST-9',brief:'A canyon relay station has gone dark. Sweep the desert outpost, neutralize the sentry drones, and reach the uplink.',theme:0,count:4},
 {name:'Blackout Run',code:'OP-02 / DEEP STRIKE',sector:'VANTA-4',brief:'The signal leads to an abandoned power complex. Fight through its industrial perimeter and secure the uplink.',theme:1,count:5},
 {name:'Last Light',code:'OP-03 / EXTRACTION',sector:'ASH-0',brief:'Final approach to the extraction beacon. The whole zone is awake. Reach the beacon and get out.',theme:2,count:6}
];
const state={mode:'menu',mission:0,hp:100,kills:0,started:0,weapon:0,fire:false,fireCd:0,mouse:false,keys:{},velocity:new THREE.Vector3(),heading:0,pitch:0,roll:0,toastTimer:0,hitTimer:0,damageCd:0,shake:0,cleared:false};
const weaponDefs=[{name:'VULCAN / 20MM',rate:.115,damage:34,color:0xc9ff81,spread:.012},{name:'PULSE / ION',rate:.38,damage:74,color:0x66eaff,spread:.004},{name:'MICRO / MISSILE',rate:.75,damage:150,color:0xffad66,spread:.02}];
let enemies=[],bullets=[],particles=[],pickup=null,exitBeacon=null,objects=[],audio=null;
function audioShot(type){try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.type=type===1?'sine':'sawtooth';o.frequency.setValueAtTime(type===1?620:type===2?120:170,audio.currentTime);o.frequency.exponentialRampToValueAtTime(45,audio.currentTime+.11);g.gain.setValueAtTime(type===2?.12:.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.13);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.14)}catch{}}
const mat=(color,roughness=.8,metalness=.05)=>new THREE.MeshStandardMaterial({color,roughness,metalness});
function mesh(geo,material,parent=world,pos=[0,0,0]){let o=new THREE.Mesh(geo,material);o.position.set(...pos);o.castShadow=true;o.receiveShadow=true;parent.add(o);if(parent===world)objects.push(o);return o}
function box(x,y,z,w,h,d,material,parent=world){return mesh(new THREE.BoxGeometry(w,h,d),material,parent,[x,y,z])}
function rand(seed){let x=Math.sin(seed*127.1+missionSeed*311.7)*43758.5453;return x-Math.floor(x)}let missionSeed=1;
const arena={size:56,ground:null};
function makeRock(x,z,scale,color){let geo=new THREE.DodecahedronGeometry(1,1);let m=mesh(geo,mat(color),world,[x,scale*.38,z]);m.scale.set(scale*(.7+rand(x+z)*.5),scale*(.5+rand(x-z)*.5),scale*(.7+rand(x*z+3)*.5));m.rotation.set(rand(z+2)*.4,rand(x+9)*6,rand(z+4)*.3);return m}
function makeBuilding(x,z,w,h,d,color,glow=false){let m=mat(color,.84,.15);box(x,h/2,z,w,h,d,m);let trim=mat('#4a554e',.45,.55);box(x,h+.08,z,w+.12,.16,d+.12,trim);let n=Math.max(1,Math.floor(w/1.3));for(let i=0;i<n;i++){let wx=x-w*.38+i*(w*.76/Math.max(1,n-1));let win=mat(glow?'#ffca7b':'#243d3a',.35,.3);let panel=box(wx,h*.58,z-d/2-.012,.16,.42,.025,win);if(glow){let l=new THREE.PointLight('#ffad65',.45,5);l.position.set(wx,h*.58,z-d/2-.3);world.add(l)}}return m}
function makeAntenna(x,z){let metal=mat('#63685e',.48,.7),pole=mesh(new THREE.CylinderGeometry(.035,.07,4,8),metal,world,[x,2,z]);let dish=mesh(new THREE.SphereGeometry(.6,14,8,0,Math.PI*2,0,Math.PI*.48),mat('#a3a58c',.4,.65),world,[x,3.6,z]);dish.rotation.x=Math.PI;for(let i=-1;i<=1;i++)box(x+i*.35,2.5,z,.035,1.5,.04,metal);let light=mesh(new THREE.SphereGeometry(.11,8,8),new THREE.MeshBasicMaterial({color:'#ff4f57'}),world,[x,4.1,z]);let p=new THREE.PointLight('#ff3448',1.5,4);p.position.copy(light.position);world.add(p)}
function buildArena(index){world.clear();objects=[];enemies=[];bullets=[];particles=[];missionSeed=index+1;let cfg=missions[index],desert=['#8d8060','#626955','#6e7064'][index],rock=['#75644e','#454b47','#55504a'][index],building=['#605744','#353f3d','#514a42'][index];scene.background.set(index===1?'#899c9e':index===2?'#908e8c':'#95a7a7');scene.fog.color.copy(scene.background);scene.fog.density=index===1?.016:.0115;
let groundMat=mat(desert,1,0);arena.ground=mesh(new THREE.PlaneGeometry(130,130,1,1),groundMat);arena.ground.rotation.x=-Math.PI/2;arena.ground.position.y=-.12;arena.ground.receiveShadow=true;
let grid=new THREE.GridHelper(120,60,'#514f42','#736e57');grid.position.y=-.105;grid.material.transparent=true;grid.material.opacity=.16;world.add(grid);
// perimeter broken canyon ridges, with intentionally open flight lanes
for(let side of [-1,1])for(let i=0;i<11;i++){let z=-27+i*5.3,x=side*(25+rand(i+side*5)*4),sz=2.5+rand(i+23)*3.4;makeRock(x,z,sz,rock);if(i%3===0)makeRock(x-side*2,z+2,sz*.8,desert)}
// landmark rocks scattered around the combat bowl
for(let i=0;i<28;i++){let x=(rand(i+50)-.5)*46,z=(rand(i+90)-.5)*46;if(Math.hypot(x,z)<8)continue;makeRock(x,z,1.2+rand(i+4)*2.6,i%4===0?desert:rock)}
if(index===0){makeBuilding(-12,-15,7,5,6,building);makeBuilding(13,-12,8,4,7,building);makeBuilding(-15,12,6,4,8,building);makeBuilding(13,14,8,6,6,building);makeAntenna(-9,-14);makeAntenna(16,13)}
if(index===1){for(let i=0;i<5;i++){let x=-18+i*9;makeBuilding(x,-15,5,7+(i%2)*2,6,building,true);makeBuilding(x,15,5,5,6,building,true)}for(let i=0;i<4;i++)box(-18+i*12,2.5,0,7,.45,.5,mat('#626d65',.45,.65));makeAntenna(19,-15);makeAntenna(-20,16)}
if(index===2){for(let i=0;i<7;i++){let x=-21+i*7;makeBuilding(x,-17,4.2,3+rand(i+7)*5,5,building,i%2===0);makeBuilding(x,16,4.2,4+rand(i+2)*4,5,building,i%3===0)}for(let i=0;i<8;i++){let x=(rand(i+100)-.5)*38,z=(rand(i+120)-.5)*28;if(Math.abs(z)<5)z+=Math.sign(z||1)*8;let fire=mesh(new THREE.ConeGeometry(.5+rand(i)*.5,2+rand(i+4)*2,7),new THREE.MeshBasicMaterial({color:i%2?'#ff7438':'#ffca60'}),world,[x,1,z]);fire.rotation.z=Math.PI;let light=new THREE.PointLight('#ff793f',2.2,8);light.position.set(x,1,z);world.add(light)}makeAntenna(22,-18)}
// flight obstacles and striped towers
for(let i=0;i<12;i++){let x=(rand(i+200)-.5)*42,z=(rand(i+230)-.5)*42;if(Math.hypot(x,z)<11)continue;let y=2+rand(i+33)*5;let tower=mesh(new THREE.CylinderGeometry(.28+rand(i)*.3,.5, y*2,7),mat(i%2?'#4e594d':'#6f6651',.8,.25),world,[x,y,z]);if(i%3===0){let lamp=mesh(new THREE.SphereGeometry(.1,8,8),new THREE.MeshBasicMaterial({color:'#ff554d'}),world,[x,y*2,z]);let point=new THREE.PointLight('#ff3434',.8,4);point.position.copy(lamp.position);world.add(point)}}
// uplink extraction beacon at the far edge
exitBeacon=new THREE.Group();exitBeacon.position.set(0,0,-23);world.add(exitBeacon);let ring=mesh(new THREE.TorusGeometry(1.3,.09,10,32),mat('#d2ff72',.25,.65),exitBeacon,[0,1.2,0]);ring.rotation.x=Math.PI/2;let ring2=mesh(new THREE.TorusGeometry(2,.035,8,32),new THREE.MeshBasicMaterial({color:'#d2ff72',transparent:true,opacity:.5}),exitBeacon,[0,1.2,0]);ring2.rotation.x=Math.PI/2;mesh(new THREE.CylinderGeometry(.06,.06,5,8),new THREE.MeshBasicMaterial({color:'#d2ff72'}),exitBeacon,[0,2.4,0]);let beaconLight=new THREE.PointLight('#bcff57',4,16);beaconLight.position.set(0,2.3,0);exitBeacon.add(beaconLight);exitBeacon.userData.ring=ring;exitBeacon.userData.ring2=ring2;
for(let i=0;i<cfg.count;i++){let ang=(i/cfg.count)*Math.PI*2+.4,r=13+rand(i+300)*5;spawnEnemy(Math.cos(ang)*r, -Math.sin(ang)*r)}
for(let i=0;i<70;i++){let geo=new THREE.BufferGeometry();let p=new Float32Array([rand(i+500)*100-50,2+rand(i+600)*18,rand(i+700)*100-50]);geo.setAttribute('position',new THREE.BufferAttribute(p,3));let stars=new THREE.Points(geo,new THREE.PointsMaterial({color:'#f3dca7',size:.045,transparent:true,opacity:.42}));world.add(stars)}
}
function spawnEnemy(x,z){let objectStart=objects.length;let g=new THREE.Group();g.position.set(x,2.8,z);world.add(g);let body=mat('#202722',.44,.68),edge=mat('#667163',.35,.7),red=new THREE.MeshStandardMaterial({color:'#ff4e54',emissive:'#ff1920',emissiveIntensity:2});let core=mesh(new THREE.IcosahedronGeometry(.56,1),body,g);core.scale.set(1.15,.58,.86);for(let i=0;i<4;i++){let a=i*Math.PI/2+.4;let arm=mesh(new THREE.BoxGeometry(1.55,.1,.13),edge,g,[Math.cos(a)*.74,0,Math.sin(a)*.74]);arm.rotation.y=-a;let motor=mesh(new THREE.CylinderGeometry(.18,.18,.14,10),body,g,[Math.cos(a)*1.42,.05,Math.sin(a)*1.42]);let rotor=mesh(new THREE.BoxGeometry(.78,.025,.07),edge,g,[Math.cos(a)*1.42,.17,Math.sin(a)*1.42]);rotor.userData.rotor=true;let eye=mesh(new THREE.SphereGeometry(.105,10,8),red,g,[Math.cos(a)*.45,.1,Math.sin(a)*.45]);eye.material=red}let hpBack=mesh(new THREE.PlaneGeometry(1.3,.09),new THREE.MeshBasicMaterial({color:'#252a25',side:THREE.DoubleSide}),g,[0,1.02,0]);let hpFill=mesh(new THREE.PlaneGeometry(1.25,.055),new THREE.MeshBasicMaterial({color:'#ff5b58',side:THREE.DoubleSide}),g,[0,1.02,.005]);enemies.push({g,hp:100,maxHp:100,alive:true,shoot:.8+Math.random()*1.5,phase:Math.random()*6,hit:0,hpFill,core});objects.length=objectStart}
function droneModel(){let g=new THREE.Group();camera.add(g);g.position.set(0,-.43,-1.12);let black=mat('#111a18',.35,.72),edge=mat('#424f43',.25,.8),lime=new THREE.MeshBasicMaterial({color:'#d2ff72'});let body=mesh(new THREE.BoxGeometry(.32,.16,.48),black,g,[0,0,0]);body.rotation.x=-.12;mesh(new THREE.BoxGeometry(.22,.055,.2),edge,g,[0,.105,-.09]);mesh(new THREE.BoxGeometry(.06,.055,.1),lime,g,[0,.11,-.2]);for(let i of [-1,1]){let arm=mesh(new THREE.BoxGeometry(.58,.055,.08),black,g,[i*.31,.035,.05]);arm.rotation.y=i*.21;for(let z of [-1,1]){let rotor=mesh(new THREE.CylinderGeometry(.11,.11,.04,16),edge,g,[i*.55,.06,z*.19]);let blades=mesh(new THREE.BoxGeometry(.31,.012,.026),lime,g,[i*.55,.085,z*.19]);blades.userData.rotor=true}}let barrel=mesh(new THREE.CylinderGeometry(.035,.045,.34,10),edge,g,[0,-.04,-.38]);barrel.rotation.x=Math.PI/2;let light=new THREE.PointLight('#d2ff72',.5,2);light.position.set(0,.2,0);g.add(light);return g}let playerDrone=droneModel();objects.length=0;
function loadMission(){state.mode='playing';state.hp=100;state.kills=0;state.weapon=0;state.velocity.set(0,0,0);state.heading=0;state.pitch=0;state.roll=0;state.started=performance.now();state.cleared=false;state.damageCd=0;camera.position.set(0,2.8,17);camera.rotation.set(0,0,0);buildArena(state.mission);$('#menu').classList.add('hidden');$('#result').classList.add('hidden');$('#pauseScreen').classList.add('hidden');$('#hud').classList.remove('hidden');$('#pauseButton').classList.remove('hidden');$('#missionCode').textContent=missions[state.mission].code;$('#missionName').textContent=missions[state.mission].name.toUpperCase();$('#objectiveText').textContent='HOSTILES 0 / '+enemies.length;$('#hostileCount').textContent=String(enemies.length).padStart(2,'0');$('#hp').textContent='100';$('#hpBar').style.width='100%';if(innerWidth>700)canvas.requestPointerLock?.()}
function pause(){if(state.mode==='playing'){state.mode='pause';$('#pauseScreen').classList.remove('hidden');document.exitPointerLock?.()}else if(state.mode==='pause'){state.mode='playing';$('#pauseScreen').classList.add('hidden');if(innerWidth>700)canvas.requestPointerLock?.();last=performance.now()}}
function fire(){if(state.mode!=='playing'||state.fireCd>0)return;let w=weaponDefs[state.weapon];state.fireCd=w.rate;audioShot(state.weapon);let dir=new THREE.Vector3(0,0,-1).applyQuaternion(camera.quaternion);dir.x+=(Math.random()-.5)*w.spread;dir.y+=(Math.random()-.5)*w.spread;dir.normalize();let start=camera.position.clone().addScaledVector(dir,.8);let ray=new THREE.Raycaster(start,dir,0,90);let candidates=[];for(let e of enemies)if(e.alive){e.g.updateMatrixWorld(true);candidates.push(e.core)}let hit=ray.intersectObjects(candidates,false)[0];if(hit){let enemy=enemies.find(e=>e.core===hit.object);if(enemy){enemy.hp-=w.damage;enemy.hit=.14;enemy.hpFill.scale.x=Math.max(.001,enemy.hp/enemy.maxHp);enemy.hpFill.position.x=-(1-enemy.hp/enemy.maxHp)*.62;state.hitTimer=.12;spawnImpact(hit.point,w.color);if(enemy.hp<=0){enemy.alive=false;world.remove(enemy.g);state.kills++;showToast('HOSTILE DRONE NEUTRALIZED')}else showToast('TARGET DAMAGED')}}else{let end=start.clone().addScaledVector(dir,75);let beam=new THREE.Line(new THREE.BufferGeometry().setFromPoints([start,end]),new THREE.LineBasicMaterial({color:w.color,transparent:true,opacity:.72}));fx.add(beam);setTimeout(()=>{fx.remove(beam);beam.geometry.dispose()},55)}state.shake=.06}
function spawnImpact(pos,color){for(let i=0;i<7;i++){let p=mesh(new THREE.SphereGeometry(.035+Math.random()*.04,5,5),new THREE.MeshBasicMaterial({color,transparent:true}),fx,pos.toArray());let vel=new THREE.Vector3(Math.random()-.5,Math.random()-.3,Math.random()-.5).normalize().multiplyScalar(1+Math.random()*3);particles.push({m:p,v:vel,t:.35+Math.random()*.3})}}
function showToast(t){let el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>el.classList.remove('show'),1050)}
function update(dt,t){if(state.mode!=='playing')return;dt=Math.min(dt,.04);state.fireCd-=dt;state.damageCd-=dt;state.hitTimer-=dt;state.shake=Math.max(0,state.shake-dt);if(state.fire)fire();const k=state.keys;let forward=(k.KeyW?1:0)-(k.KeyS?1:0),strafe=(k.KeyD?1:0)-(k.KeyA?1:0),vertical=(k.Space?1:0)-(k.ControlLeft||k.ControlRight?1:0);let boost=k.ShiftLeft||k.ShiftRight?1.8:1,speed=10*boost;let forward3=new THREE.Vector3(-Math.sin(state.heading),0,-Math.cos(state.heading)),right3=new THREE.Vector3(Math.cos(state.heading),0,-Math.sin(state.heading));let target=new THREE.Vector3().addScaledVector(forward3,forward*speed).addScaledVector(right3,strafe*speed);target.y=vertical*speed*.72;state.velocity.lerp(target,1-Math.exp(-dt*(forward||strafe||vertical?3.8:2.2)));camera.position.addScaledVector(state.velocity,dt);camera.position.x=THREE.MathUtils.clamp(camera.position.x,-24,24);camera.position.z=THREE.MathUtils.clamp(camera.position.z,-25,25);camera.position.y=THREE.MathUtils.clamp(camera.position.y,1.4,13);camera.rotation.set(state.pitch,state.heading,state.roll,'YXZ');let driftRoll=THREE.MathUtils.clamp(-strafe*.12,-.18,.18);state.roll=THREE.MathUtils.damp(state.roll,driftRoll,3,dt);playerDrone.rotation.z=state.roll*.6;playerDrone.position.y=-.43+Math.sin(t*.004)*.012+(vertical*.02);let altitude=Math.round(camera.position.y*15);$('#altitude').textContent=String(altitude).padStart(3,'0');$('#hp').textContent=state.hp;$('#hpBar').style.width=state.hp+'%';
for(let e of enemies){if(!e.alive)continue;e.phase+=dt*3;e.g.position.y=2.5+Math.sin(e.phase)*.44;let toPlayer=camera.position.clone().sub(e.g.position);let dist=toPlayer.length();if(dist<31){e.g.lookAt(camera.position);if(dist>7){let move=toPlayer.normalize().multiplyScalar(dt*(dist<13?1.3:.65));e.g.position.add(move);e.g.position.x=THREE.MathUtils.clamp(e.g.position.x,-24,24);e.g.position.z=THREE.MathUtils.clamp(e.g.position.z,-24,24)}e.shoot-=dt;if(e.shoot<=0&&dist<26&&state.damageCd<=0){let dir=toPlayer.normalize(),ray=new THREE.Raycaster(e.g.position,dir,0,dist);let wallHits=ray.intersectObjects(objects,false);if(!wallHits.length||wallHits[0].distance>dist-1){state.hp=Math.max(0,state.hp-(5+Math.floor(Math.random()*5)));state.damageCd=.55;$('#damage').classList.add('show');setTimeout(()=>$('#damage').classList.remove('show'),130);e.shoot=1.2+Math.random()*1.2;audioShot(2);if(state.hp<=0){finish(false);return}}else e.shoot=.5}}for(let c of e.g.children)if(c.userData.rotor)c.rotation.y+=dt*35}
let alive=enemies.filter(e=>e.alive).length;$('#hostileCount').textContent=String(alive).padStart(2,'0');$('#objectiveText').textContent=(state.cleared?'REACH EXTRACTION':'HOSTILES '+(enemies.length-alive)+' / '+enemies.length);if(alive===0&&!state.cleared){state.cleared=true;showToast('AIRSPACE SECURE // EXTRACTION BEACON ACTIVE')}if(state.cleared&&camera.position.distanceTo(exitBeacon.position)<3){finish(true);return}if(exitBeacon){exitBeacon.userData.ring.rotation.z+=dt*.65;exitBeacon.userData.ring2.rotation.z-=dt*.35;let pulse=1+Math.sin(t*.003)*.12;exitBeacon.userData.ring.scale.setScalar(pulse)}for(let p of particles){p.t-=dt;p.m.position.addScaledVector(p.v,dt);p.m.material.opacity=Math.max(0,p.t*2)}particles=particles.filter(p=>{if(p.t<=0){fx.remove(p.m);p.m.geometry.dispose();return false}return true});if(state.shake){camera.position.x+=(Math.random()-.5)*state.shake*.1}}
function finish(win){state.mode='result';state.fire=false;document.exitPointerLock?.();$('#pauseButton').classList.add('hidden');$('#hud').classList.add('hidden');$('#result').classList.remove('hidden');$('#resultEyebrow').textContent=win?'OPERATION COMPLETE':'DRONE LINK LOST';$('#resultTitle').innerHTML=win?(state.mission===2?'CAMPAIGN<br>COMPLETE':'SECTOR<br>SECURED'):'DRONE<br>DESTROYED';$('#resultCopy').textContent=win?(state.mission===2?'All three sectors are quiet. Northstar command confirms extraction. Campaign complete.':'Hostile airspace is clear. Extraction beacon reached. Stand by for the next operation.'):'The drone has been disabled in the exclusion zone. Reinitialize to redeploy.';$('#resultKills').textContent=state.kills+' / '+missions[state.mission].count;$('#resultHull').textContent=state.hp+'%';let sec=Math.floor((performance.now()-state.started)/1000);$('#resultTime').textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');$('#continueButton').textContent=win&&state.mission<2?'NEXT OPERATION →':win?'CAMPAIGN COMPLETE':'REDEPLOY ↻'}
function updateMenu(){let el=$('#missions');el.innerHTML='';missions.forEach((m,i)=>{let row=document.createElement('div');row.className='missionRow '+(i===state.mission?'active ':'')+(i<state.mission?'done':'');row.innerHTML=`<div class="number">0${i+1}</div><div><strong>${m.name}</strong><small>${m.sector} // ${m.brief}</small></div><div class="status">${i<state.mission?'CLEARED':i===state.mission?'READY':'LOCKED'}</div>`;el.appendChild(row)});$('#opLabel').textContent='0'+(state.mission+1)+' / 03';$('#sectorLabel').textContent=missions[state.mission].sector}
function loop(t){requestAnimationFrame(loop);let dt=Math.min((t-last)/1000,.05);last=t;if(state.mode==='playing')update(dt,t);else if(state.mode==='menu'){camera.position.set(0,8,24);camera.lookAt(0,0,0);camera.position.x=Math.sin(t*.00012)*5;camera.lookAt(0,0,-5);world.rotation.y=Math.sin(t*.00015)*.09}renderer.render(scene,camera)}let last=performance.now();requestAnimationFrame(loop);
$('#startButton').onclick=()=>{world.rotation.y=0;loadMission()};$('#pauseButton').onclick=pause;$('#resumeButton').onclick=pause;$('#abortButton').onclick=()=>{state.mode='menu';$('#pauseScreen').classList.add('hidden');$('#hud').classList.add('hidden');$('#pauseButton').classList.add('hidden');$('#menu').classList.remove('hidden');document.exitPointerLock?.();updateMenu()};$('#continueButton').onclick=()=>{if(state.hp===0){}else if(state.mission<2)state.mission++;else state.mission=0;$('#result').classList.add('hidden');$('#menu').classList.remove('hidden');state.mode='menu';updateMenu()};$('#campaignButton').onclick=()=>{state.mission=0;$('#result').classList.add('hidden');$('#menu').classList.remove('hidden');state.mode='menu';updateMenu()};
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6))});addEventListener('keydown',e=>{state.keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape')pause();if(e.code==='KeyQ'&&state.mode==='playing'){state.weapon=(state.weapon+1)%weaponDefs.length;$('#weaponName').textContent=weaponDefs[state.weapon].name;showToast('WEAPON SELECTED // '+weaponDefs[state.weapon].name)}});addEventListener('keyup',e=>state.keys[e.code]=false);canvas.addEventListener('click',()=>{if(state.mode==='playing'&&innerWidth>700){canvas.requestPointerLock?.();state.fire=true;fire()}});addEventListener('mousedown',()=>{if(state.mode==='playing'&&document.pointerLockElement===canvas){state.fire=true;fire()}});addEventListener('mouseup',()=>state.fire=false);addEventListener('mousemove',e=>{if(state.mode==='playing'&&document.pointerLockElement===canvas){state.heading-=e.movementX*.0023;state.pitch=THREE.MathUtils.clamp(state.pitch-e.movementY*.0019,-1.1,1.1)}});addEventListener('contextmenu',e=>e.preventDefault());buildArena(0);updateMenu();
