const $=s=>document.querySelector(s);
export class GameUI {
  constructor(){this.elapsed=0;this.toastTimer=0;this.feed=[];this.feedRoot=$('#killFeed');this.onPlay=()=>{};this.onResume=()=>{};this.onAbort=()=>{};this.onCamera=()=>{};this.onRestart=()=>{};this.countdownTimer=0;this.countdownValue=0;
    $('#playButton').onclick=()=>this.onPlay();$('#resumeButton').onclick=()=>this.onResume();$('#quitButton').onclick=()=>this.onAbort();$('#cameraToggle').onclick=()=>this.onCamera();$('#againButton').onclick=()=>this.onRestart();$('#pauseButton').onclick=()=>this.onResume();
  }
  showMatch(){ $('#menu').classList.add('hidden');$('#pauseOverlay').classList.add('hidden');$('#endOverlay').classList.add('hidden');$('#hud').classList.remove('hidden');$('#pauseButton').classList.remove('hidden');$('#cameraToggle').classList.remove('hidden');this.elapsed=0;$('#matchClock').textContent='00:00'; }
  showMenu(){ $('#menu').classList.remove('hidden');$('#hud').classList.add('hidden');$('#pauseButton').classList.add('hidden');$('#cameraToggle').classList.add('hidden');$('#pauseOverlay').classList.add('hidden');$('#endOverlay').classList.add('hidden');$('#countdown').classList.add('hidden'); }
  countdown(done){const root=$('#countdown'),number=$('#countdownNumber');root.classList.remove('hidden');this.countdownValue=3;number.textContent='3';clearInterval(this.countdownTimer);this.countdownTimer=setInterval(()=>{if(root.classList.contains('hidden')){clearInterval(this.countdownTimer);return}this.countdownValue--;if(this.countdownValue<=0){clearInterval(this.countdownTimer);root.classList.add('hidden');done()}else number.textContent=this.countdownValue},700);}
  pause(){ $('#pauseOverlay').classList.remove('hidden'); }
  resume(){ $('#pauseOverlay').classList.add('hidden'); }
  setCamera(mode){$('#cameraToggle').innerHTML='CAMERA <b>'+(mode==='fpv'?'FPV':'CHASE')+'</b> <kbd>V</kbd>';}
  clock(dt){this.elapsed+=dt;const s=Math.floor(this.elapsed);$('#matchClock').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
  hud(state,combat,roster){$('#healthValue').textContent=Math.ceil(state.health);$('#healthBar').style.width=state.health+'%';$('#boostValue').textContent=Math.ceil(state.boost);$('#boostBar').style.width=state.boost+'%';$('#ammoValue').textContent=combat.reload>0?'··':String(combat.ammo).padStart(2,'0');$('#weaponLabel').textContent=combat.weapon.name;$('#weaponHint').textContent=combat.reload>0?'RELOADING · R TO RELOAD':combat.weapon.mode+' · R RELOAD';$('#reloadBar').style.width=combat.reload>0?((1-combat.reload/combat.weapon.reload)*100)+'%':'100%';const rows=$('#scoreRows');rows.replaceChildren();for(const member of roster){const row=document.createElement('div');row.className='scoreRow'+(member.you?' you':'');row.innerHTML='<span>'+(member.you?'◆  ':'◇  ')+member.name+'</span><b class="scoreValue">'+String(member.score).padStart(2,'0')+'</b>';rows.append(row)}const reticle=$('#reticle');reticle.classList.toggle('focus',state.focus);reticle.classList.toggle('hit',combat.hitTime>0);$('#hitConfirm').classList.toggle('show',combat.hitTime>0);$('#speedFX').classList.toggle('active',state.boosting);$('#damageFX').classList.toggle('active',state.damageFlash>0);}
  toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>el.classList.remove('show'),1000)}
  killFeed(killer,victim){this.feed.unshift({killer,victim,time:Date.now()});this.feed=this.feed.slice(0,4);this.feedRoot.innerHTML=this.feed.map(e=>'<div><b>'+e.killer+'</b>  ▸  '+e.victim+'</div>').join('')}
  end(win,roster){$('#countdown').classList.add('hidden');$('#pauseOverlay').classList.add('hidden');$('#hud').classList.add('hidden');$('#pauseButton').classList.add('hidden');$('#cameraToggle').classList.add('hidden');$('#endOverlay').classList.remove('hidden');$('#endKicker').textContent=win?'MATCH COMPLETE // MVP FLIGHT':'MATCH COMPLETE // FLIGHT LOG';$('#endTitle').innerHTML=win?'AIRSPACE<br><span>DOMINATED.</span>':'RUN IT<br><span>BACK.</span>';$('#endCopy').textContent=win?'District secured. The rest of the lobby just learned to look up.':'Close match. Tune your flight path and claim the next sortie.';let player=roster.find(x=>x.you);let top=roster.reduce((a,b)=>a.score>b.score?a:b);$('#finalScore').textContent='YOUR SCORE   '+String(player.score).padStart(2,'0')+'   /   MVP '+top.name;}
}
